/*

	A* USER
	B* ROLE
	C* USER_ROLE

*/

-- A* USER

CREATE TABLE GENERIC.USER (
	USER_ID BIGINT(14) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(20) NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL,
    CREATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATOR_ID BIGINT(14) DEFAULT -1,
    LAST_UPDATOR_ID BIGINT(14) DEFAULT -1,
    ACTIVE TINYINT(1) DEFAULT 1
);

ALTER TABLE GENERIC.USER ADD UNIQUE (USERNAME);

-- B* ROLE

CREATE TABLE GENERIC.ROLE (
	ROLE_ID BIGINT(14) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ROLE_NAME VARCHAR(20) NOT NULL,
    CREATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATOR_ID BIGINT(14) DEFAULT -1,
    LAST_UPDATOR_ID BIGINT(14) DEFAULT -1,
    ACTIVE TINYINT(1) DEFAULT 1
);

ALTER TABLE GENERIC.ROLE ADD UNIQUE (ROLE_NAME);


-- C* USER_ROLE

CREATE TABLE GENERIC.USER_ROLE (
	USER_ROLE_ID BIGINT(14) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	USER_ID BIGINT(14) NOT NULL,
    ROLE_ID BIGINT(14) NOT NULL,
    CREATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATOR_ID BIGINT(14) DEFAULT -1,
    LAST_UPDATOR_ID BIGINT(14) DEFAULT -1,
    ACTIVE TINYINT(1) DEFAULT 1
);

ALTER TABLE GENERIC.USER_ROLE
ADD CONSTRAINT FK_UR_U
FOREIGN KEY (USER_ID)
REFERENCES GENERIC.USER(USER_ID);

ALTER TABLE GENERIC.USER_ROLE
ADD CONSTRAINT FK_UR_R
FOREIGN KEY (ROLE_ID)
REFERENCES GENERIC.ROLE(ROLE_ID);